name = "backend"
compatibility_date = "2024-08-15"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWIwMmM2Y2QtNWFhNi00ZDdlLTllMGQtNjA5MGM2NGY3OTM3IiwidGVuYW50X2lkIjoiZmEyMmE3N2Y0ODg4NDI5NzQ1Yzc0NDg5OGYyMGFmMWFjNmQ3NDk5NjNiNGMzNWU4MmU5MDg1YTU0YzdmODcwOCIsImludGVybmFsX3NlY3JldCI6IjNlZGViMGZkLTE3YjItNGVlNy1iNWE0LWM5OGQ3NmM1YTVhMSJ9.InnTbV6aBUaEQy6tkLy4MJVKP3TNy54t-ui1uyQYNlA"
JWT_SECRET = "KUSHAL_WILL_GET_PPO"